version: 2.1

# Steps shared by chain jobs

default_docker_image: &default_docker_image
  docker:
    - image: circleci/node:10.16.0

commands:
  setup_job:
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test RPC
          command: yarn chain
          background: true

jobs:
  checkout_and_compile:
    <<: *default_docker_image
    working_directory: ~/index-deployments
    steps:
      - checkout
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Fetch Dependencies
          command: yarn install
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile Contracts
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/index-deployments
  test:
    <<: *default_docker_image
    working_directory: ~/index-deployments
    steps:
      - setup_job
      - run:
          name: Hardhat Test
          command: yarn test

  deployment:
    <<: *default_docker_image
    working_directory: ~/index-deployments
    steps:
      - setup_job
      - run:
          name: Test Deployment
          command: yarn deploy:local

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
      - deployment:
          requires:
            - checkout_and_compile
